node {
    stage('SCM Checkout'){
        git credentialsId: 'bit', url: 'https://Avinash-m@bitbucket.org/scrummybearsgroup/orders.git'
    }
    stage('Mvn Package & Unit Test'){
    def mvnHome = tool name: 'maven-3', type: 'maven'
    def mvnCMD = "${mvnHome}/bin/mvn"
    sh  "${mvnCMD} clean package"
    }
    
    stage('SonarQube Analysis & Acceptance Testing') {
    def mvnHome =  tool name: 'maven-3', type: 'maven'
    withSonarQubeEnv('sonar-6') { 
    sh "${mvnHome}/bin/mvn sonar:sonar"
        }
    }
    
    stage("Quality Gate"){
          timeout(time: 1, unit: 'HOURS') {
              def qg = waitForQualityGate()
              if (qg.status != 'OK') {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
              }
          }
         }

     stage('Build Docker Image'){
     sh 'docker build -t sai288/my-app:order1.1 .'
    }
    stage('Push Docker Image to DocketHub'){
     sh 'docker login -u sai288 -p swefall2018'
     sh 'docker push sai288/my-app:order1.1'
    }
}